name: Python API Tests with Allure History

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Allure CLI
        env:
          ALLURE_VERSION: 2.35.1
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
              ca-certificates \
              apt-transport-https \
              wget \
              unzip \
              openjdk-21-jre-headless \
              && sudo rm -rf /var/lib/apt/lists/*
          
          wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip -O /tmp/allure.zip
          unzip /tmp/allure.zip -d /opt/
          sudo ln -s /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure
          rm /tmp/allure.zip

      - name: Restore Allure history
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-history || true
        continue-on-error: true  

      - name: Run tests
        run: |
          pytest tests/ --alluredir=allure-results || true

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report --history allure-history

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history
